version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: flask_postgres
    environment:
      POSTGRES_USER: tutormatch
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: tutormatch_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: